### ISSUE TITLE
TestSmtpClient.SentMails broken with SendAsync

### ISSUE THREAD

**Issue by swegner** [smsohan/MvcMailer#127]
Because `TestSmtpClient._sentMails` is attributed with `[ThreadStatic]`, the value is not available when the `SendAsync` API is used because the mail is sent on a separate thread.  This breaks a valuable test hook in `MvcMailMessage`.

Is there any particular reason `_sentMails` needs `[ThreadStatic]`?  Leaving it off would fix it.

**Comment by smsohan** [comment]
See the example test for testing send async on the wiki.

---

Sent from my iPhone
Sohan SM

On Mar 3, 2014, at 1:28 PM, Scott Wegner notifications@github.com wrote:

Because TestSmtpClient._sentMails is attributed with [ThreadStatic], the
value is not available when the SendAsync API is used because the mail is
sent on a separate thread. This breaks a valuable test hook in
MvcMailMessage.

Is there any particular reason _sentMails needs [ThreadStatic]? Leaving it
off would fix it.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/smsohan/MvcMailer/issues/127
.

**Comment by swegner** [comment]
The test cases for `SendAsync` execute synchronously. Here's a repro: 6a902ea27ce81e34c464070c7fabbe37a97a36c6

```
[Test]
public void SendAsync_from_background_thread_should_add_to_sent_mails()
{
    var messageA = new MailMessage { From = new MailAddress("hello@example.com"), Subject = "Hello", Body = "There" };
    messageA.To.Add("hi@example.com");

    // Use actual thread for deterministic repro; this also works with async/await as long as
    // task scheduler performs work in separate thread.
    Thread backgroundThread = new Thread(() => _testSmtpClient.SendAsync(messageA));
    backgroundThread.Start();
    backgroundThread.Join();

    Assert.AreEqual(1, TestSmtpClient.SentMails.Count);
}

```

**Comment by swegner** [comment]
Thanks!
